### ISSUE TITLE
codecov issue

### ISSUE THREAD

**Issue by sneko** [ryansonshine/typescript-npm-package-template#11]
Hi,

I used your template yesterday and it uses
```
        "codecov": "^3.8.1",
```

But at the end it downloads `3.8.2` (whereas above is available) and I get the error as mentioned in https://github.com/codecov/codecov-node/issues/324

Upgrading to
```
        "codecov": "^3.8.3",
```
helps fixing the breaking issue :) (tested & passing)

Thank you,

**Comment by ryansonshine** [comment]
Great, thanks for the contribution! I'll put in a change as soon as I get a chance.
