### ISSUE TITLE
The command in README.md replaces npm package names.

### ISSUE THREAD

**Issue by 34j** [ryansonshine/typescript-npm-package-template#22]
## Current Behavior

The following command in the README.md will replace `@ryansonshine/cz-conventional-changelog`, `@ryansonshine/commitizen` with `@$GITHUB_USER/cz-conventional-changelog`
```
sed -i.mybak "s/ryansonshine/$GITHUB_USER/g; s/typescript-npm-package-template\|my-package-name/$REPO_NAME/g; s/Ryan Sonshine/$FULL_NAME/g" package.json package-lock.json README.md
```

## Expected Behavior

Do not replace them.

## Steps to Reproduce the Problem

  1. Run the command in README.md

## Environment

- Version: 
- Platform: Win
- Node.js Version: 

I am not familiar with regular expressions and sed, so I am not sure how to solve this issue, but I think adding `; s/@$GITHUB_USER/@ryansonshine/g`will do.
```
sed -i.mybak "s/ryansonshine/$GITHUB_USER/g; s/typescript-npm-package-template\|my-package-name/$REPO_NAME/g; s/Ryan Sonshine/$FULL_NAME/g; s/@$GITHUB_USER/@ryansonshine/g" package.json package-lock.json README.md
```

**Comment by ryansonshine** [comment]
Thanks for reporting this issue, I'll take a look shortly!
